### ISSUE TITLE
Prettier editor plugins don't honour version

### ISSUE THREAD

**Issue by mattsjones** [seek-oss/sku#142]
Currently `sku` handles formatting with prettier for you and therefore owns the version of prettier. Most editors will honour your version of prettier per project by looking at the package.json. This clashes with `sku` though as the editor doesn't see prettier as a direct dependency of the app your working on and therefore uses its own internal version (which can differ).

**Comment by jahredhope** [comment]
Prettier configuration files are now created on `sku configure`.
This is automatically ran on post-install.
