### ISSUE TITLE
NODE_ENV documentation incorrect

### ISSUE THREAD

**Issue by mbfisher** [seek-oss/sku#148]
The 'Environment Variables' section of the README states that `NODE_ENV` is avaiable both on the client and server, however, `NODE_ENV` is not defined in the browser when running `sku start`.

The `DefinePlugin` is configured by composing [`envVars`](https://github.com/seek-oss/sku/blob/master/config/webpack/webpack.config.js#L107), which does not contain `NODE_ENV`, and some [production specific](https://github.com/seek-oss/sku/blob/master/config/webpack/webpack.config.js#L221) variables, which does include `NODE_ENV`, but only when it's value is `production`.

If I log the plugins section of my computed webpack config I get:

```
[ DefinePlugin {
    definitions:
     { 'process.env.SKU_TENANT': '""',
       'process.env.SKU_ENV': '"development"',
       'process.env.PORT': '8080' } },
```

Is this a bug, i.e. we should be setting `NODE_ENV` in development, or do you prefere `SKU_ENV` and  the docs are out of date? My preference would be to include `NODE_ENV` as it's so widely used.

Mike

**Comment by mbfisher** [comment]
I've let this go a bit stale - unless there are any objections I'm going to raise a PR that set's both `NODE_ENV` and `SKU_ENV` in client code and update the docs.

**Comment by jahredhope** [comment]
I believe this has been addressed with https://github.com/seek-oss/sku/pull/215
Please re-open if the issue still exists.
