### ISSUE TITLE
Update Braid and remove deprecated components from template

### ISSUE THREAD

**Issue by tadhglewis** [seek-oss/sku#594]
When setting up a project using sku, the template is using BulletList and Bullet, these are deprecated - https://seek-oss.github.io/braid-design-system/components/BulletList

Todo
- [x] update braid-design-system in sku
- [x] Follow migration guide for https://seek-oss.github.io/braid-design-system/components/List/releases to replace BulletList

**Comment by jahredhope** [comment]
Hi @tadhglewis , great issue and thank-you for calling this out.

I agree the template should be updated, and probably needs a good looking over for anything else that might have changed.

Given the `Todo` list in this Issue have you already got a PR in mind? Otherwise I'll work on a change myself.

**Comment by tadhglewis** [comment]
@jahredhope I was gonna work on a PR although as you mentioned, needs a good look over.

I can put through a PR with anything I find and if I get stuck with any other changes that need doing with the latest Braid version I'll open up a draft PR for someone to continue on.

Thoughts?

**Comment by jahredhope** [comment]
Sounds good, thanks
